services:
  db:
    image: mysql:8.0.32
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: basedatos
      MYSQL_ROOT_HOST: '%'
    command: >
      --authentication-policy=mysql_native_password
      --bind-address=0.0.0.0
    ports:
      - "192.168.0.101:3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
    name: mysql_data